import type { AllyId, SymphonyAlly } from '../types/game';

export const ALLIES: Record<AllyId, SymphonyAlly> = {
  percival: {
    id: 'percival',
    trueName: 'Percival',
    instrument: 'Percussion',
    corruptedName: 'The Drumming Colossus',
    summonAbility: 'Grand Drum Roll',
    summonEffect: 'Massive AoE stun — all enemies lose their next turn',
    rpCost: 50,
    freed: false,
    zone: 8,
  },
  flaura: {
    id: 'flaura',
    trueName: 'Flaura',
    instrument: 'Flute',
    corruptedName: 'The Aria Wraith',
    summonAbility: 'Ethereal Aria',
    summonEffect: 'Heal the party (20% of each member\'s maxHp) and charm all weak enemies for 1 turn',
    rpCost: 50,
    freed: false,
    zone: 9,
  },
  buccina: {
    id: 'buccina',
    trueName: 'Buccina',
    instrument: 'Trumpet',
    corruptedName: 'The War Horn Berserker',
    summonAbility: 'Fanfare of Light',
    summonEffect: 'High single-target damage (3× base) and party Attack buff (+20 Power) for 3 turns',
    rpCost: 50,
    freed: false,
    zone: 10,
  },
  claribel: {
    id: 'claribel',
    trueName: 'Claribel',
    instrument: 'Clarinet',
    corruptedName: 'The Register Phantom',
    summonAbility: 'Crystalline Cascade',
    summonEffect: '5-hit magic attack spread across all enemies',
    rpCost: 50,
    freed: false,
    zone: 10,
  },
  hautbois: {
    id: 'hautbois',
    trueName: 'Hautbois',
    instrument: 'Oboe',
    corruptedName: 'The Double-Reed Specter',
    summonAbility: 'The Tuning A',
    summonEffect: 'Restores Accuracy buff to all party members and heals 15% HP each',
    rpCost: 50,
    freed: false,
    zone: 9,
  },
  waldhorn: {
    id: 'waldhorn',
    trueName: 'Waldhorn',
    instrument: 'French Horn',
    corruptedName: 'The Forest Guardian',
    summonAbility: 'Mountain Echo',
    summonEffect: 'Deals damage that reverberates 3× over 3 turns (delayed AoE)',
    rpCost: 50,
    freed: false,
    zone: 9,
  },
  sackbut: {
    id: 'sackbut',
    trueName: 'Sackbut',
    instrument: 'Trombone',
    corruptedName: 'The Sliding Chaos Knight',
    summonAbility: 'Slide into Shadow',
    summonEffect: 'Debuffs all enemies (−20 Accuracy) and deals high damage to one target',
    rpCost: 50,
    freed: false,
    zone: 10,
  },
  euphonia: {
    id: 'euphonia',
    trueName: 'Euphonia',
    instrument: 'Euphonium / Tuba',
    corruptedName: 'The Stone Colossus',
    summonAbility: 'Pedal Tone Quake',
    summonEffect: 'Massive AoE damage and a party damage-shield for 2 turns',
    rpCost: 50,
    freed: false,
    zone: 11,
  },
  fagotto: {
    id: 'fagotto',
    trueName: 'Fagotto',
    instrument: 'Bassoon',
    corruptedName: 'The Ancient Revenant',
    summonAbility: 'Cantus Antiquus',
    summonEffect: 'Revives any fallen party member at full HP and applies a barrier (absorbs next hit) to all',
    rpCost: 50,
    freed: false,
    zone: 11,
  },
  adolpha: {
    id: 'adolpha',
    trueName: 'Adolpha',
    instrument: 'Alto Saxophone',
    corruptedName: 'The Sultry Shadow',
    summonAbility: 'Cool Jazz Improv',
    summonEffect: 'Random powerful effect (high variance) — one of: full-party heal, massive single-target damage, AoE stun, or triple RP gain',
    rpCost: 50,
    freed: false,
    zone: 11,
  },
  grand_symphony: {
    id: 'grand_symphony',
    trueName: 'The Grand Symphony',
    instrument: 'All Instruments',
    corruptedName: '—',
    summonAbility: 'Sacred Score',
    summonEffect: 'All freed Symphony members perform together. Massive damage to all enemies and full-party HP restore.',
    rpCost: 200,
    freed: false,
    zone: 12,
  },
};
