import type { InstrumentId } from '../types/game';
import type { StatusType } from './statusEffects';

export type EnemyTier = 1 | 2 | 3 | 4 | 5 | 6;

export interface EnemyDef {
  id: string;
  tier: EnemyTier;
  zone: number;          // first zone where this enemy appears
  name: string;
  description: string;
  power: number;
  maxHp: number;
  attackDescription: string;
  specialAttackName?: string;
  specialAttackChallengeType?: string;
  debuff?: StatusType;
  debuffDuration?: number;
  debuffChance?: number;  // chance the enemy inflicts its status on a standard attack (default 0.4)
  vulnerableTo: InstrumentId[];
  isBoss: boolean;
  phase2Threshold?: number;
  lore?: string;
}

export const ENEMIES: Record<string, EnemyDef> = {
  // ── Tier 1: Accidentals ──────────────────────────────────────────────────────
  flatling: {
    id: 'flatling',
    tier: 1,
    zone: 1,
    name: 'Flatling',
    description: 'Small, blue-grey, droopy. Emits flat, sagging notes.',
    power: 8,
    maxHp: 60,
    attackDescription: 'Drains Accuracy — pitches harder to land',
    specialAttackName: 'Flat Pulse',
    specialAttackChallengeType: 'aural_pitch_spy',
    debuff: 'blind',
    debuffDuration: 2,
    vulnerableTo: ['oboe', 'clarinet', 'flute'],
    isBoss: false,
    lore: 'Born when a note is played flat and forgotten.',
  },
  sharp_creature: {
    id: 'sharp_creature',
    tier: 1,
    zone: 1,
    name: 'Sharp',
    description: 'Red-orange, spiked, aggressive. Screeches piercing tones.',
    power: 12,
    maxHp: 50,
    attackDescription: 'Fast physical spike attack, high crit chance',
    specialAttackName: 'Shriek',
    specialAttackChallengeType: 'aural_pitch_spy',
    vulnerableTo: ['oboe', 'clarinet', 'flute'],
    isBoss: false,
  },
  natural_creature: {
    id: 'natural_creature',
    tier: 1,
    zone: 1,
    name: 'Natural',
    description: 'White, neutral, annoying. Appears alongside others.',
    power: 6,
    maxHp: 40,
    attackDescription: 'Cancels debuffs on ally enemies; dispels player buffs',
    vulnerableTo: ['oboe', 'clarinet', 'flute'],
    isBoss: false,
  },
  double_flat_wretch: {
    id: 'double_flat_wretch',
    tier: 1,
    zone: 3,
    name: 'Double-Flat Wretch',
    description: 'Larger Flatling variant, deeper droop, more powerful.',
    power: 14,
    maxHp: 90,
    attackDescription: 'Stacks Accuracy drain; forces a lower note challenge',
    specialAttackName: 'Deep Sag',
    specialAttackChallengeType: 'aural_pitch_spy',
    debuff: 'blind',
    debuffDuration: 3,
    vulnerableTo: ['oboe', 'clarinet', 'flute'],
    isBoss: false,
  },

  // ── Tier 2: Chronotons ────────────────────────────────────────────────────────
  chronoton_scout: {
    id: 'chronoton_scout',
    tier: 2,
    zone: 3,
    name: 'Chronoton Scout',
    description: 'Tick-tock robot marching in perfect 4/4.',
    power: 10,
    maxHp: 70,
    attackDescription: 'Attack lands every 4 beats — completely predictable',
    specialAttackName: 'Metronomic Strike',
    specialAttackChallengeType: 'aural_rhythm_echo',
    vulnerableTo: ['percussion', 'clarinet', 'alto_sax'],
    isBoss: false,
  },
  chronoton_shifter: {
    id: 'chronoton_shifter',
    tier: 2,
    zone: 3,
    name: 'Chronoton Shifter',
    description: 'Shifts time signature mid-battle without warning.',
    power: 14,
    maxHp: 80,
    attackDescription: 'Changes attack rhythm suddenly; disrupts player timing',
    specialAttackName: 'Time Shift',
    specialAttackChallengeType: 'aural_rhythm_echo',
    vulnerableTo: ['percussion', 'clarinet', 'alto_sax'],
    isBoss: false,
  },

  shard_phantom: {
    id: 'shard_phantom',
    tier: 1,
    zone: 2,
    name: 'The Footlight Phantom',
    description: 'A mischievous theater-sprite that haunts old concert halls, drawn out by the swell of live music. Harmless but maddening — it flits through the hall scattering sheet music and tangling the ensemble\'s carefully built sound.',
    power: 20,
    maxHp: 200,
    attackDescription: 'Page Scatter — jumbles your sense of pitch relationships',
    specialAttackName: 'Footlight Flicker',
    specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'confusion',
    debuffDuration: 2,
    vulnerableTo: ['bassoon', 'oboe', 'french_horn'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'No one is sure how long it has nested in the Theory Wing\'s old recital hall. It means no harm — it simply cannot resist a good crescendo.',
  },

  // ── Bosses ─────────────────────────────────────────────────────────────────────
  enchanted_music_stand: {
    id: 'enchanted_music_stand',
    tier: 1,
    zone: 1,
    name: 'The Enchanted Music Stand',
    description: 'A practice room stand possessed by a wandering Flatling. It rattles the music and drains your Accuracy.',
    power: 18,
    maxHp: 180,
    attackDescription: 'Rattles the score — Accuracy drain + rhythm disruption',
    specialAttackName: 'Score Rattle',
    specialAttackChallengeType: 'aural_pitch_spy',
    debuff: 'blind',
    debuffDuration: 2,
    vulnerableTo: ['oboe', 'clarinet', 'flute'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'The stand has stood in Practice Room 4 for thirty years. No one remembers who left the Flatling there.',
  },
  flat_dragon: {
    id: 'flat_dragon',
    tier: 1,
    zone: 1,
    name: 'The Flat Dragon',
    description: 'A dragon whose very breath pulls everything flat. Your accuracy window is halved for the entire fight.',
    power: 22,
    maxHp: 240,
    attackDescription: 'Flat Breath — all pitch challenges have halved tolerance this battle',
    specialAttackName: 'Flat Breath',
    specialAttackChallengeType: 'aural_pitch_spy',
    debuff: 'blind',
    debuffDuration: 999,
    vulnerableTo: ['oboe', 'flute', 'clarinet'],
    isBoss: true,
    phase2Threshold: 0.4,
    lore: 'Ancient texts describe this creature as the "Flattener of Harmonics."',
  },
  interval_imp: {
    id: 'interval_imp',
    tier: 2,
    zone: 2,
    name: 'The Interval Imp',
    description: 'Born from a mis-played tritone in the theory classroom. Chaotic, scrambles player timing.',
    power: 20,
    maxHp: 200,
    attackDescription: 'Tritone Scramble — confuses all active buffs',
    specialAttackName: 'Tritone Scramble',
    specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'confusion',
    debuffDuration: 1,
    vulnerableTo: ['bassoon', 'oboe', 'french_horn'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'Maestro Persichetti swears the theory classroom was perfectly normal before this year.',
  },

  // ── Act 2 · Zone 5 — The Melodious Meadows ───────────────────────────────────
  stray_melody: {
    id: 'stray_melody',
    tier: 1,
    zone: 5,
    name: 'Stray Melody',
    description: 'A scrap of music torn loose in the Shattering, drifting the meadows with no player left to guide it.',
    power: 16,
    maxHp: 120,
    attackDescription: 'A wandering, off-key phrase that nicks at your focus',
    specialAttackName: 'Wrong Note',
    specialAttackChallengeType: 'aural_pitch_spy',
    debuff: 'blind',
    debuffDuration: 1,
    vulnerableTo: ['oboe', 'clarinet', 'flute'],
    isBoss: false,
  },
  aria_wraith: {
    id: 'aria_wraith',
    tier: 1,
    zone: 5,
    name: 'The Aria Wraith',
    description: 'Maestra Flaura, your flute professor, hollowed to a single endless note. She drifts above a field of crops she has kept standing long after they died.',
    power: 22,
    maxHp: 280,
    attackDescription: 'A sustained, sorrowful tone that drags at your limbs',
    specialAttackName: 'Endless Aria',
    specialAttackChallengeType: 'aural_melody_mapper',
    debuff: 'slow',
    debuffDuration: 2,
    vulnerableTo: ['trumpet', 'trombone', 'tuba'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'She will not stop playing. She does not seem to remember how.',
  },
  war_horn_berserker: {
    id: 'war_horn_berserker',
    tier: 1,
    zone: 5,
    name: 'The War Horn Berserker',
    description: 'Maestro Cornelius, your trumpet professor, reduced to a single blaring call to charge. He does not know you — only sounds the attack, again and again.',
    power: 26,
    maxHp: 320,
    attackDescription: 'A blaring fanfare driving a reckless, heavy strike',
    specialAttackName: 'Endless Charge',
    specialAttackChallengeType: 'aural_rhythm_echo',
    debuff: 'confusion',
    debuffDuration: 1,
    vulnerableTo: ['clarinet', 'percussion', 'alto_sax'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'Beneath the noise he is still searching for someone — a brother, lost in the same storm that took him.',
  },

  // ── Act 2 · Zone 6 — Sands of Time (Register Phantoms + maestro bosses) ───────
  chalumeau_phantom: {
    id: 'chalumeau_phantom',
    tier: 1,
    zone: 6,
    name: 'Chalumeau Phantom',
    description: 'A low, dark shape that haunts the deepest Chaconne Caves, droning in the clarinet\'s bottom register.',
    power: 17,
    maxHp: 130,
    attackDescription: 'A heavy, sluggish low blow',
    specialAttackName: 'Deep Drone',
    specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'slow',
    debuffDuration: 1,
    vulnerableTo: ['oboe', 'flute', 'trumpet'],
    isBoss: false,
  },
  clarion_phantom: {
    id: 'clarion_phantom',
    tier: 1,
    zone: 6,
    name: 'Clarion Phantom',
    description: 'A bright, piercing shape that flits through the upper caves, shrieking in the clarinet\'s clarion register.',
    power: 19,
    maxHp: 95,
    attackDescription: 'A fast, ringing strike with a vicious edge',
    specialAttackName: 'Clarion Shriek',
    specialAttackChallengeType: 'aural_pitch_spy',
    debuff: 'blind',
    debuffDuration: 1,
    vulnerableTo: ['oboe', 'clarinet', 'flute'],
    isBoss: false,
  },
  bassetta: {
    id: 'bassetta',
    tier: 1,
    zone: 6,
    name: 'Bassetto',
    description: 'Maestro Clarence, your clarinet professor, scattered across every register at once — a short-tempered nomad whose wail rises and plunges without warning.',
    power: 24,
    maxHp: 300,
    attackDescription: 'A register-leaping wail that lashes from nowhere',
    specialAttackName: 'Break Crossing',
    specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'confusion',
    debuffDuration: 2,
    vulnerableTo: ['oboe', 'flute', 'french_horn'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'The desert wind carries his three registers in three directions. Pin all three and he is himself again.',
  },
  caucophonus: {
    id: 'caucophonus',
    tier: 2,
    zone: 6,
    name: 'Caucophonus',
    description: 'Maestra Paige, your percussion professor, reduced to a tireless engine of production — stamping out discord-laced goods at the Caesura Crossing.',
    power: 28,
    maxHp: 360,
    attackDescription: 'A relentless, mechanical hammering on the downbeat',
    specialAttackName: 'Discord Assembly',
    specialAttackChallengeType: 'aural_rhythm_echo',
    debuff: 'cramped',
    debuffDuration: 1,
    vulnerableTo: ['clarinet', 'alto_sax', 'percussion'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'She builds without pause and without purpose. Break his rhythm and the workshop falls silent at last.',
  },

  // ── Act 2 · Zone 7 — Clef Cliffs (the first Discordian outpost) ───────────────
  discordian_sentry: {
    id: 'discordian_sentry',
    tier: 5,
    zone: 7,
    name: 'Discordian Sentry',
    description: 'One of Vexus\'s made things — an instrument given a soldier\'s shape and no player at all, posted on the cliff road.',
    power: 19,
    maxHp: 130,
    attackDescription: 'A drilled, mechanical strike in lockstep',
    specialAttackName: 'Lockstep',
    specialAttackChallengeType: 'aural_rhythm_echo',
    debuff: 'slow',
    debuffDuration: 1,
    vulnerableTo: ['oboe', 'clarinet', 'alto_sax'],
    isBoss: false,
  },
  sound_shadow: {
    id: 'sound_shadow',
    tier: 1,
    zone: 7,
    name: 'The Sound Shadow',
    description: 'Maestra Adolpha, your saxophone professor, reduced to a hall of borrowed shapes — a mimic with no self left at the center.',
    power: 24,
    maxHp: 300,
    attackDescription: 'A stolen attack worn like a mask',
    specialAttackName: 'Borrowed Form',
    specialAttackChallengeType: 'aural_chord_oracle',
    debuff: 'confusion',
    debuffDuration: 2,
    vulnerableTo: ['clarinet', 'percussion', 'alto_sax'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'She wears a hundred faces and none of them are hers. Cut through the copies to find Adolpha underneath.',
  },
  lieutenant_contra: {
    id: 'lieutenant_contra',
    tier: 6,
    zone: 7,
    name: 'Lieutenant Contra',
    description: 'A contrabass clarinet given command and cruelty by Vexus\'s tritonal magic — the first of his made lieutenants you face. It holds the outpost, and two of your professors, in its grip.',
    power: 30,
    maxHp: 420,
    attackDescription: 'A subsonic blast that rattles you to the teeth',
    specialAttackName: "Conductor's Command",
    specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'cramped',
    debuffDuration: 1,
    vulnerableTo: ['flute', 'oboe', 'trumpet'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'It was never a musician. It only ever followed orders — and gave them.',
  },
  sliding_chaos_knight: {
    id: 'sliding_chaos_knight',
    tier: 1,
    zone: 7,
    name: 'The Sliding Chaos Knight',
    description: 'Maestro Sackbut, your trombone professor, turned to one wild, destructive glissando that sweeps everything in reach.',
    power: 28,
    maxHp: 360,
    attackDescription: 'A roaring slide that scythes across the field',
    specialAttackName: 'Glissando Sweep',
    specialAttackChallengeType: 'aural_pitch_spy',
    debuff: 'blind',
    debuffDuration: 2,
    vulnerableTo: ['oboe', 'flute', 'clarinet'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'No aim, no malice — just a slide swung at the whole world. Time it, and he is yours.',
  },
  stone_colossus: {
    id: 'stone_colossus',
    tier: 1,
    zone: 7,
    name: 'The Stone Colossus',
    description: 'Maestro Torbult, your euphonium professor, sunk into one immovable low tone — a foundation holding up nothing, refusing to move.',
    power: 26,
    maxHp: 440,
    attackDescription: 'A slow, ground-shaking pedal-tone slam',
    specialAttackName: 'Pedal Quake',
    specialAttackChallengeType: 'aural_rhythm_echo',
    debuff: 'slow',
    debuffDuration: 2,
    vulnerableTo: ['alto_sax', 'clarinet', 'trumpet'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'Endless, patient, unbreakable — until the right notes find the crack in the foundation.',
  },

  // ── Act 2 · Zone 8 — Forgotten Forest (the finale) ───────────────────────────
  echoing_wisp: {
    id: 'echoing_wisp',
    tier: 3,
    zone: 8,
    name: 'Echoing Wisp',
    description: 'A knot of fog and feedback drifting the Forgotten Forest, repeating a scrap of someone else\'s call.',
    power: 21,
    maxHp: 150,
    attackDescription: 'A disorienting echo that comes from everywhere at once',
    specialAttackName: 'Hall of Echoes',
    specialAttackChallengeType: 'aural_melody_mapper',
    debuff: 'confusion',
    debuffDuration: 1,
    vulnerableTo: ['bassoon', 'oboe', 'french_horn'],
    isBoss: false,
  },
  forest_flogger: {
    id: 'forest_flogger',
    tier: 1,
    zone: 8,
    name: 'The Forest Flogger',
    description: 'Maestro Waldhorn, your french horn professor, whose endless echoing calls have become the fog itself — confusing and corrupting all who enter.',
    power: 28,
    maxHp: 360,
    attackDescription: 'A horn call that strikes from a direction you can never quite place',
    specialAttackName: 'Echoing Call',
    specialAttackChallengeType: 'aural_melody_mapper',
    debuff: 'confusion',
    debuffDuration: 2,
    vulnerableTo: ['bassoon', 'oboe', 'clarinet'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'His brother has crossed a desert and a mountain to reach him. Quiet the calls, and the fog will lift.',
  },
  double_reed_specter: {
    id: 'double_reed_specter',
    tier: 4,
    zone: 8,
    name: 'The Double-Reed Specter',
    description: 'Maestra Hautbois, your oboe professor, reduced to a single relentless purpose: fell the ancient trees, harvest the cane, make more reeds, forever.',
    power: 26,
    maxHp: 340,
    attackDescription: 'A piercing, precise reed-shriek that finds every gap',
    specialAttackName: 'Reed Harvest',
    specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'vulnerable',
    debuffDuration: 2,
    vulnerableTo: ['trumpet', 'trombone', 'percussion'],
    isBoss: true,
    phase2Threshold: 0.5,
    lore: 'When she comes back to herself, she will look at what her hands have done — and lay the reed down for good.',
  },
  ancient_revenant: {
    id: 'ancient_revenant',
    tier: 4,
    zone: 8,
    name: 'The Ancient Revenant',
    description: 'Maestro Fagotto, your bassoon professor and the eldest of the Maestros, hollowed to a hoarder of old knowledge he can no longer use. The last shard to reclaim.',
    power: 32,
    maxHp: 460,
    attackDescription: 'A grinding low drone that wears down body and resolve',
    specialAttackName: 'Cantus Mortis',
    specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'poison',
    debuffDuration: 3,
    vulnerableTo: ['flute', 'oboe', 'clarinet'],
    isBoss: true,
    phase2Threshold: 0.4,
    lore: 'Free him, and the Symphony is whole again for the first time since the Renewal.',
  },

  // ── Act 3 · Zone 9 — Chromatic Coasts ────────────────────────────────────────
  wave_walker: {
    id: 'wave_walker', tier: 3, zone: 9, name: 'Wave Walker',
    description: 'A translucent thing that flows like a sound wave along the corrupted shore, passing through whatever it pleases.',
    power: 26, maxHp: 210, attackDescription: 'A phasing surge that slips past your guard',
    specialAttackName: 'Phase Tide', specialAttackChallengeType: 'aural_chord_oracle',
    debuff: 'vulnerable', debuffDuration: 2, vulnerableTo: ['trumpet', 'trombone', 'tuba'], isBoss: false,
  },
  coastal_dissonance: {
    id: 'coastal_dissonance', tier: 3, zone: 9, name: 'The Coastal Dissonance',
    description: 'Where the trail of corruption meets the sea, the surf itself has soured — a standing swell of clashing frequencies guarding the water.',
    power: 30, maxHp: 430, attackDescription: 'A crashing wall of dissonant sound',
    specialAttackName: 'Breakwater', specialAttackChallengeType: 'aural_chord_oracle',
    debuff: 'slow', debuffDuration: 2, vulnerableTo: ['trumpet', 'percussion', 'tuba'], isBoss: true, phase2Threshold: 0.5,
    lore: 'Clear it, and the way to the Fourth Wind is open.',
  },

  // ── Act 3 · Zone 10 — Syncopated Seas ────────────────────────────────────────
  rogue_wave: {
    id: 'rogue_wave', tier: 3, zone: 10, name: 'Rogue Wave',
    description: 'An off-beat swell that rears up out of nowhere, cresting against the rhythm of the sea.',
    power: 28, maxHp: 190, attackDescription: 'A syncopated slam that lands when you least expect it',
    specialAttackName: 'Offbeat Crash', specialAttackChallengeType: 'aural_rhythm_echo',
    debuff: 'cramped', debuffDuration: 1, vulnerableTo: ['percussion', 'clarinet', 'alto_sax'], isBoss: false,
  },
  the_maelstrom: {
    id: 'the_maelstrom', tier: 3, zone: 10, name: 'The Maelstrom',
    description: 'A vast rogue whirlpool that grows louder and wider with every passing moment. It must be broken quickly — or not at all.',
    power: 34, maxHp: 560, attackDescription: 'A churning vortex that drags you under',
    specialAttackName: 'Rising Swell', specialAttackChallengeType: 'aural_rhythm_echo',
    debuff: 'slow', debuffDuration: 2, vulnerableTo: ['percussion', 'trumpet', 'tuba'], isBoss: true, phase2Threshold: 0.5,
    lore: 'It is loudest just before it breaks. Hold your tempo and do not falter.',
  },

  // ── Act 3 · Zone 11 — Dissonant Dunes ────────────────────────────────────────
  cacophony_soldier: {
    id: 'cacophony_soldier', tier: 5, zone: 11, name: 'Cacophony Soldier',
    description: 'A made soldier of the Discordian Guard, far stronger when its fellows fight at its side.',
    power: 30, maxHp: 240, attackDescription: 'A drilled formation strike',
    specialAttackName: 'Close Ranks', specialAttackChallengeType: 'aural_rhythm_echo',
    debuff: 'blind', debuffDuration: 1, vulnerableTo: ['oboe', 'clarinet', 'alto_sax'], isBoss: false,
  },
  piano_commander: {
    id: 'piano_commander', tier: 6, zone: 11, name: 'Piano',
    description: 'A Vexian knight-commander who strikes from near-silence — the soft half of the pair that holds the dunes.',
    power: 32, maxHp: 500, attackDescription: 'A whisper-quiet strike you never hear coming',
    specialAttackName: 'Sotto Voce', specialAttackChallengeType: 'aural_pitch_spy',
    debuff: 'blind', debuffDuration: 2, vulnerableTo: ['oboe', 'flute', 'trumpet'], isBoss: true, phase2Threshold: 0.5,
    lore: 'Where Forte overwhelms, Piano slips the blade in unseen.',
  },
  forte_commander: {
    id: 'forte_commander', tier: 6, zone: 11, name: 'Forte',
    description: 'A Vexian knight-commander of overwhelming force — the loud half of the pair, and the one you hear coming a mile off.',
    power: 40, maxHp: 560, attackDescription: 'A thunderous, ground-splitting blow',
    specialAttackName: 'Fortissimo', specialAttackChallengeType: 'aural_rhythm_echo',
    debuff: 'cramped', debuffDuration: 1, vulnerableTo: ['clarinet', 'percussion', 'alto_sax'], isBoss: true, phase2Threshold: 0.5,
    lore: 'Both must fall before the doors of the Hall will open.',
  },

  // ── Act 3 · Zone 12 — The Hall of Discord ────────────────────────────────────
  vexian_knight: {
    id: 'vexian_knight', tier: 6, zone: 12, name: 'Vexian Knight',
    description: "One of Vexus's personally made elite, drilled in atonal combat music. The practice rooms are full of them.",
    power: 34, maxHp: 270, attackDescription: 'An elite multi-hit combination',
    specialAttackName: 'Atonal Drill', specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'confusion', debuffDuration: 1, vulnerableTo: ['trumpet', 'oboe', 'clarinet'], isBoss: false,
  },
  ostinato_usher: {
    id: 'ostinato_usher', tier: 6, zone: 12, name: 'Ostinato, the Usher',
    description: 'A towering brass-and-gearwork automaton built to defeat unwelcome guests and drag them out of the Hall. It never tires and never varies.',
    power: 36, maxHp: 600, attackDescription: 'A relentless, repeating mechanical combination',
    specialAttackName: 'Endless Ostinato', specialAttackChallengeType: 'aural_rhythm_echo',
    debuff: 'cramped', debuffDuration: 1, vulnerableTo: ['percussion', 'clarinet', 'alto_sax'], isBoss: true, phase2Threshold: 0.5,
    lore: 'Its one trick, repeated forever — find the seam in the loop and break it.',
  },
  lieutenant_kije: {
    id: 'lieutenant_kije', tier: 6, zone: 12, name: 'Lieutenant Kije',
    description: 'A piccolo given a soldier\'s shape and tritonal cruelty — the shrill, piercing junior of the Tritone Trio.',
    power: 34, maxHp: 380, attackDescription: 'A piercing high shriek that splits your focus',
    specialAttackName: 'Piccolo Pierce', specialAttackChallengeType: 'aural_pitch_spy',
    debuff: 'blind', debuffDuration: 2, vulnerableTo: ['trombone', 'tuba', 'bassoon'], isBoss: true, phase2Threshold: 0.5,
    lore: 'The highest voice of the Trio. Silence it, and the chord loses its edge.',
  },
  commander_mesto: {
    id: 'commander_mesto', tier: 6, zone: 12, name: 'Commander Mesto',
    description: 'An English horn automaton of mournful, hollow tone — the inner voice of the Tritone Trio.',
    power: 38, maxHp: 460, attackDescription: 'A hollow, sorrowing tone that saps the will',
    specialAttackName: 'Lament', specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'slow', debuffDuration: 2, vulnerableTo: ['trumpet', 'percussion', 'clarinet'], isBoss: true, phase2Threshold: 0.5,
    lore: 'The middle voice. With it gone, the tritone cannot hold together.',
  },
  general_grave: {
    id: 'general_grave', tier: 6, zone: 12, name: 'General Grave',
    description: "A contrabassoon of crushing depth and command — Vexus's second, and the leader of the Tritone Trio.",
    power: 42, maxHp: 640, attackDescription: 'A subsonic blast that buckles your knees',
    specialAttackName: 'Grave Depths', specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'poison', debuffDuration: 3, vulnerableTo: ['flute', 'oboe', 'clarinet'], isBoss: true, phase2Threshold: 0.4,
    lore: 'The lowest voice and the last. Break the General, and the way to the stage is clear.',
  },
  vexus: {
    id: 'vexus', tier: 6, zone: 12, name: 'Vexus, the Conductor',
    description: 'The Composer\'s own appointed Conductor, who tried to prove himself the equal of his maker and broke the world. He stands on the stage, baton raised over an orchestra of player-less instruments, certain he is right.',
    power: 44, maxHp: 840, attackDescription: 'A cascade of tritonal dissonance from a hundred soulless instruments',
    specialAttackName: 'Atonal Assault', specialAttackChallengeType: 'aural_interval_quest',
    debuff: 'confusion', debuffDuration: 2, vulnerableTo: [], isBoss: true, phase2Threshold: 0.4,
    lore: 'He cannot hear what he has done. Beat back his phantom orchestra — and then answer it with living music.',
  },
};

// ── Class effectiveness (GDD: "Highly Effective ×1.5") ─────────────────────────
// An enemy's vulnerableTo lists the instrument classes whose stat emphasis
// counters its musical nature. Matching classes deal bonus damage with their
// own abilities. (Summons are the maestros' instruments, not the player's, so
// they are unaffected.)
export const EFFECTIVENESS_MULT = 1.5;

export function isHighlyEffective(def: EnemyDef, instrument: InstrumentId): boolean {
  return def.vulnerableTo.includes(instrument);
}

export type BattleId = string;

export interface BattleConfig {
  id: BattleId;
  name: string;
  enemies: string[]; // enemy ids
  zoneId: number;
  isBoss: boolean;
  isMiniBuffer: boolean;
  rewardXp: number;
  rewardCoins: number;
  rewardGearId?: string;
  victoryNarrative: string;
  defeatNarrative: string;
}

export const BATTLES: Record<BattleId, BattleConfig> = {
  // Zone 1 encounters
  z1_flatling_encounter: {
    id: 'z1_flatling_encounter',
    name: 'Flatling Encounter',
    enemies: ['flatling'],
    zoneId: 1,
    isBoss: false,
    isMiniBuffer: false,
    rewardXp: 200,
    rewardCoins: 5,
    victoryNarrative: 'The Flatling dissolves into a off-key sigh. Your pitch holds true.',
    defeatNarrative: 'The Flatling\'s influence drags your tone flat. Retreat to the Academy.',
  },
  z1_mini_boss: {
    id: 'z1_mini_boss',
    name: 'The Enchanted Music Stand',
    enemies: ['enchanted_music_stand'],
    zoneId: 1,
    isBoss: false,
    isMiniBuffer: true,
    rewardXp: 600,
    rewardCoins: 15,
    rewardGearId: 'iron_stand',
    victoryNarrative: 'The Flatling\'s grip on the stand shatters. It tips over harmlessly, an ordinary object once more.',
    defeatNarrative: 'The stand\'s rattling overwhelms your focus. You retreat to the practice hall.',
  },
  z1_boss: {
    id: 'z1_boss',
    name: 'The Graduation Trial',
    enemies: ['flat_dragon'],
    zoneId: 1,
    isBoss: true,
    isMiniBuffer: false,
    rewardXp: 1500,
    rewardCoins: 40,
    victoryNarrative: 'The Flat Dragon retreats into the mountains. The Academy cheers. Headmaster Fennelio nods.',
    defeatNarrative: 'The dragon\'s breath pulls every note flat. You withdraw to the practice halls.',
  },
  z2_mini_boss: {
    id: 'z2_mini_boss',
    name: 'The Interval Imp',
    enemies: ['interval_imp'],
    zoneId: 2,
    isBoss: false,
    isMiniBuffer: true,
    rewardXp: 600,
    rewardCoins: 15,
    victoryNarrative: 'The Interval Imp dissolves in a cascade of correctly identified intervals. Maestro Persichetti looks unsurprised.',
    defeatNarrative: 'The Imp\'s tritone scramble overwhelms your training. Retreat to the Theory Wing.',
  },
};
