import { useState } from 'react';

// Renders a retro portrait image when the asset exists, falling back to an
// emoji tile when there is no src or the file 404s (assets are generated by
// scripts/make_portraits.py and may not be present in every checkout).
export default function MaestroPortrait({ src, emoji, size, color }: {
  src?: string;
  emoji: string;
  size: number;
  color?: string;
}) {
  const [failed, setFailed] = useState(false);

  if (src && !failed) {
    return (
      <img
        src={src}
        width={size}
        height={size}
        onError={() => setFailed(true)}
        alt=""
        style={{ imageRendering: 'pixelated', objectFit: 'cover', display: 'block', width: size, height: size }}
      />
    );
  }
  return (
    <div
      className="flex items-center justify-center"
      style={{
        width: size,
        height: size,
        background: color ? `${color}18` : 'rgba(255,255,255,0.06)',
        fontSize: Math.round(size * 0.55),
        lineHeight: 1,
      }}
    >
      {emoji}
    </div>
  );
}
